libname mydata "/courses/u_coursera.org1/i_1006328/c_5333" access=readonly;

DATA new; SET mydata.gapminder_pds;

IF INCOMEPERPERSON EQ . THEN INCOMEGROUP=.;
ELSE IF INCOMEPERPERSON LE 744.239 THEN INCOMEGROUP=1;
ELSE IF INCOMEPERPERSON LE 2549.558 THEN INCOMEGROUP=2;
ELSE IF INCOMEPERPERSON LE 9425.326 THEN INCOMEGROUP=3;
ELSE IF INCOMEPERPERSON GT 9425.325 THEN INCOMEGROUP=4;

PROC SORT; BY COUNTRY;

PROC CORR; VAR URBANRATE INCOMEPERPERSON INTERNETUSERATE;

RUN;

