
libname mydata "/courses/u_coursera.org1/i_1006328/c_5333" access=readonly;


DATA new; SET mydata.gapminder_pds;

/*Data Munging*/
/*Creating INTERNETSCORE tabulating INTERNETUSERATE*/

IF INTERNETUSERATE < 0 THEN INTERNETSCORE = .;
ELSE IF INTERNETUSERATE < 3 THEN INTERNETSCORE = 0;
ELSE IF INTERNETUSERATE < 7.5 THEN INTERNETSCORE = 1;
ELSE IF INTERNETUSERATE < 12.33 THEN INTERNETSCORE = 2;
ELSE IF INTERNETUSERATE < 20 THEN INTERNETSCORE = 3;
ELSE IF INTERNETUSERATE < 31.5 THEN INTERNETSCORE = 4;
ELSE IF INTERNETUSERATE < 40.6 THEN INTERNETSCORE = 5;
ELSE IF INTERNETUSERATE < 49 THEN INTERNETSCORE = 6;
ELSE IF INTERNETUSERATE < 65.2 THEN INTERNETSCORE = 7;
ELSE IF INTERNETUSERATE < 78 THEN INTERNETSCORE = 8;
ELSE IF INTERNETUSERATE < 100 THEN INTERNETSCORE = 9;


/* To see the association of POLICYSCORE and  INTERNETSCORE */
IF POLITYSCORE = . THEN POLITYSCORE2 = .;
ELSE IF POLITYSCORE <= 0 THEN POLITYSCORE2=0;
ELSE POLITYSCORE2=1;



PROC SORT; BY COUNTRY;



PROC PRINT; VAR COUNTRY INTERNETUSERATE POLITYSCORE INTERNETSCORE;

PROC FREQ; TABLES COUNTRY INTERNETUSERATE POLITYSCORE POLITYSCORE2 INTERNETSCORE;

run;